### ISSUE TITLE
Read of splay tree mutates it

### ISSUE THREAD

**Issue by alanz** [haskell/lsp#165]
According to https://en.wikipedia.org/wiki/Splay_tree,

> Good performance for a splay tree depends on the fact that it is self-optimizing, in that frequently accessed nodes will move nearer to the root where they can be accessed more quickly.

So, do we or any of the library clients need to do a stateful read from the splay tree?

Or does the normal update via `DidChange` messages give us enough locality already?

**Comment by michaelpj** [comment]
I think this is obsoleted by the switch to `text-rope`.
