### ISSUE TITLE
Add support for semantic highlighting (LSP 3.16)

### ISSUE THREAD

**Issue by alanz** [haskell/lsp#240]
See emacs-lsp/lsp-mode#1482 where they discuss adding support in emacs lsp-mode. Which means vscode and lsp-mode will be supporting this shortly.

**Comment by jneira** [comment]
Yeah, it is inckuded in the incoming 3.16 spec version: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#version_3_16_0
I've added it in the general issue about the spec: https://github.com/alanz/haskell-lsp/issues/134

**Comment by jneira** [comment]
Closed by #314
