### ISSUE TITLE
[RFC] Unify prepareRename and rename handlers

### ISSUE THREAD

**Issue by kirelagin** [haskell/lsp#266]
As a sort of a follow up to #265, I was thinking that it is actually kind of weird and inconvenient that the server implementation needs to provide two separate handlers, while their implementations, in practice, are likely very related.

As a reminder, when the user wants to rename a symbol, if both handlers are implemented, the client first sends a `prepareRename` request with the location and expects to receive either `null` if renaming at this location is impossible, or the range of the name being changed. If renaming is possible, it will prompt for the new name, and then send a `rename` request with the location and the new name.

So my proposal is to replace these with a single handler, something along the lines of:

```haskell
handleRename
  :: TextDocumentPositionParams  -- ^ Position
  -> Either
        (Maybe ResponseError)  -- ← Can’t rename here or some other error happened
        (Range |? RangeWithPlaceholder, Text -> Either ResponseError WorkspaceEdit)
        -- ↑ PrepareRename response       ↑ Function from `newName` to Rename response
```

And then a pair of helpers can be used to build a pair of `prepareRename` and `rename` handlers that are guaranteed to be consistent with each other.

**Comment by michaelpj** [comment]
I think this is pretty sensible, but we can do this on the user side. @joyfulmantis has done something similar for resolve handlers in HLS.

**Comment by michaelpj** [comment]
I think this shouldn't be done in `lsp` itself, but in downstream libraries.
