### ISSUE TITLE
Missing HasTextDocument and HasPosition instances for many parameter structs

### ISSUE THREAD

**Issue by fwcd** [haskell/lsp#303]
Some parameter structs have both a text document and a position, but are missing `HasTextDocument` and `HasPosition` instances:

* `HoverParams` (see [here](https://hackage.haskell.org/package/lsp-types-1.0.0.1/docs/Language-LSP-Types.html#t:HoverParams))
* `DefinitionParams` (see [here](https://hackage.haskell.org/package/lsp-types-1.0.0.1/docs/Language-LSP-Types.html#t:DefinitionParams))
* `SignatureHelpParams` (see [here](https://hackage.haskell.org/package/lsp-types-1.0.0.1/docs/Language-LSP-Types.html#t:SignatureHelpParams))
* `TypeDefinitionParams` (see [here](https://hackage.haskell.org/package/lsp-types-1.0.0.1/docs/Language-LSP-Types.html#t:TypeDefinitionParams))
* `ImplementationParams` (see [here](https://hackage.haskell.org/package/lsp-types-1.0.0.1/docs/Language-LSP-Types.html#t:ImplementationParams))
  ...

**Comment by michaelpj** [comment]
I think this is just missing stuff in `Lenses.hs`. It's annoyingly difficult to keep that file up to date. Maybe I'll try and write a small script to check for omissions...

**Comment by michaelpj** [comment]
I believe these particular ones were actually fixed on master already!

**Comment by jneira** [comment]
> 
> 
> I believe these particular ones were actually fixed on master already!

So i think we can close this one, thanks @fwcd @michaelpj
