### ISSUE TITLE
Support MarkdownClientCapabilities

### ISSUE THREAD

**Issue by isovector** [haskell/lsp#329]
I'd like to be able to inspect the `MarkdownClientCapabilities` object in LSP 3.16

https://microsoft.github.io/language-server-protocol/specification#markupContent

**Comment by michaelpj** [comment]
I've got a PR up for this, but I don't know if it will necessarily help you. I don't think clients are obliged to send this if they support markdown, e.g. I know that `lsp-mode` doesn't.

**Comment by michaelpj** [comment]
Ah, I suspect what you actually want is this: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#hoverClientCapabilities

**Comment by michaelpj** [comment]
(Which is already supported!)
