### ISSUE TITLE
How to get haskell-language-server to work _on_ lsp codebase?

### ISSUE THREAD

**Issue by sidkshatriya** [haskell/lsp#336]
I'm trying to get code navigation/auto completion working with `haskell/lsp` but it does not work. I'm using the stack workflow.

I complied lsp with  `stack build --stack-yaml stack-8.10.4` and it went without a hitch

Now, when I try to run `haskell-language-server` in the lsp directory I get 

```
...
...
Completed (0 files worked, 89 files failed)
```

Investigating further I find that there is a `hie.yaml` but that has cradle setting for `cabal` only. I'm much more comfortable with stack and rather not get into a cabal workflow.

How do I get things working with haskell-language-server + stack _on_ the lsp codebase?

**Comment by sidkshatriya** [comment]
I was able to get things working in the following way. This is probably not the the recommended workflow but it seems to be working:

```
$ cd lsp
$ stack build --stack-yaml stack-8.10.4
# get into a ghc 8.10.4 context
$ stack exec bash
$ haskell-language-server # cabal now does a build in the context of the ghc 8.10.4 environment
# [...]
# [...]
# Completed (86 files worked, 3 files failed)
$ <run your editor now -- autocompletion etc works now> 
```

Is there a more elegant approach?

**Comment by jneira** [comment]
mmm I think hls choose cabal cause there is a hie.yaml in the root dir forcing it to use cabal
So deleting it would open the implicit way to choose the build tool. Don't remember right now the criteria but I would start to delete `dist-newstyle`.

Probably the existing hie.yaml should be deleted, as the implicit setup will work.

**Comment by michaelpj** [comment]
Yeah, implicit setup is pretty good these days. I think removing the `hie.yaml` and `gitignore`ing it is good. Then people can write their own one locally if they want to pick stack or cabal.
