### ISSUE TITLE
Hackage ci fails to build lsp-types-1.3.0.0

### ISSUE THREAD

**Issue by jneira** [haskell/lsp#349]
From https://github.com/haskell/lsp/issues/348#issuecomment-890574810 by @bkomuves

----------------------

Both the Hackage CI and the Matrix Builder (I'm not sure if these are separate entities or not?) fails to build lsp-types-1.3.0.0: 

* https://matrix.hackage.haskell.org/#/package/lsp-types/
* https://hackage.haskell.org/package/lsp-types-1.3.0.0/reports/

which in turn also means that there is no browsable documentation on Hackage.

Since it builds locally (with ghc 8.6.5 in my case), I would guess that the reason is maybe that some dependencies have a not-strict-enough version bound?

**Comment by jneira** [comment]
Cant reproduce the build error with ghc-8.10.5

**Comment by bkomuves** [comment]
#263 may be related (the build error messages look very similar, and the apparent reason behind it looks believable too)

**Comment by jneira** [comment]
weird it is not reproduced locally, the project does not set the hackage index in cabal.project :thinking: 
i am trying with ghc-8.10.2, the used one by hackage ci

**Comment by jneira** [comment]
It is picking `dependent-sum-0.7.1.0` locally instead the used one in hackage ci `dependent-sum-0.6.2.0` cause we are using a custom dependent-sum version in cabal.project

https://github.com/haskell/lsp/blob/dec07c6182f9c42abdac1a043caff7bcff85f81e/cabal.project#L28-L33 :facepalm:

**Comment by jneira** [comment]
working on it

**Comment by jneira** [comment]
This is still not fixed and it is not possible to make a revision adding new libraries, so a new minor version is needed

**Comment by jneira** [comment]
Opened issue upstream https://github.com/obsidiansystems/dependent-sum/issues/61, to being able to remove the inclusion of `dependent-sum` in the .cabal file (it is a transitive dependency and we should not have it there)

**Comment by jneira** [comment]
Published https://hackage.haskell.org/package/lsp-types-1.3.0.1, i hope this one will work 🤞

**Comment by jneira** [comment]
@bkomuves the hackage build for lsp-types-1.3.0.1 has been succesful: https://hackage.haskell.org/package/lsp-types-1.3.0.1/reports/1
