### ISSUE TITLE
On Hackage lsp-types release restricts to aeson <1.6

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/lsp#373]
Seen that `lsp-types` was released with 2.0 support, but then the revision was made to `< 1.6` https://hackage.haskell.org/package/lsp-types-1.3.0.1/revisions/.

So in the future, a new release with working support of `aeson >= 2.0.1` would contribute into HLS having full support for `9.0.1`.

Since `brittany` released support of `9.0.1` requiring `aeson >= 2.0.1`: https://hackage.haskell.org/package/brittany
That with `aeson < 1.6` here currently makes a restriction that prevents Cabal from solving bounds during HLS build for 9.0.1 with enabled `brittany` plugin:
https://github.com/haskell/haskell-language-server/runs/4498074985?check_suite_focus=true

**Comment by jneira** [comment]
We will need a new lsp release with aeson-2.0 support

**Comment by michaelpj** [comment]
I think that revision was to stop the old release from picking the new `aeson`, I think we just haven't done a release since we fixed it.

**Comment by jneira** [comment]
> Not sure if hls or its deps will need more changes though

https://github.com/ennocramer/floskell/issues/68

**Comment by jneira** [comment]
> 

https://github.com/ndmitchell/hlint/issues/1328

**Comment by michaelpj** [comment]
@jneira I think you're the person who can do Hackage releases. Should we go ahead and do one? I don't think there's anything we're especially waiting for.

**Comment by jneira** [comment]
well want to check if hls including the test suite is ok against LSP master before the release

**Comment by jneira** [comment]
> Yeah, I just made a hackage account so I can help out with stuff like this :)

done for the three packages living here

**Comment by jneira** [comment]
> well want to check if hls including the test suite is ok against LSP master before the release
> 
the aeson-2 thing is being more complex, so I will open a pr in hls only using master of LSP packages to do the sanity check before the release

**Comment by michaelpj** [comment]
I have a WIP branch for this, it's a fair amount of churn for dealing with the numeric type changes. Happy to keep at it, or I can push it so you can start from there.

**Comment by michaelpj** [comment]
https://github.com/michaelpj/haskell-language-server/tree/mpj/wip-hls-lsp-upgrade

**Comment by michaelpj** [comment]
Released a new version that works.
