### ISSUE TITLE
Cannot build with GHC 9.2.1

### ISSUE THREAD

**Issue by wrengr** [haskell/lsp#375]
[lsp-types-1.3.0.1](https://hackage.haskell.org/package/lsp-types) has an upper bound on base which prevents building with GHC 9.2.1. This in turn blocks [hls-floskell-plugin](https://hackage.haskell.org/package/hls-floskell-plugin) which in turn blocks [hls](https://hackage.haskell.org/package/haskell-language-server), even though both of those packages allow base-4.16

**Comment by michaelpj** [comment]
I tried to improve things [here](https://github.com/haskell/lsp/pull/377), but we're still blocked on a few upstream issues.

**Comment by michaelpj** [comment]
Fixed.
