### ISSUE TITLE
stack build error

### ISSUE THREAD

**Issue by daquexian** [haskell/lsp#395]
> Error: While constructing the build plan, the following exceptions were encountered:
> 
> In the dependencies for lsp-types-1.4.0.1:
>     text-rope needed, but the stack configuration has no specified version  (latest matching version is 0.1)
> needed since lsp-types is a build target.
> 
> Some different approaches to resolving this:
> 
>   * Recommended action: try adding the following to your extra-deps in /home/dev/files/repos/haskell-lsp/stack.yaml:
> 
> - text-rope-0.1@sha256:0654bbff798a5b32d63de75bdfce3ea9a7b9abf1e3325c620878af9d48061e33,1953
> 
> Plan construction failed.

**Comment by jneira** [comment]
thanks for the report, the stack build should be checked in CI, would you mind open a pr with the fix?

**Comment by daquexian** [comment]
> thanks for the report, the stack build should be checked in CI, would you mind open a pr with the fix?

Ok! I opened a pr #396
