### ISSUE TITLE
Missing `null` case of response to `textDocument/definition` request

### ISSUE THREAD

**Issue by lehmacdj** [haskell/lsp#411]
```haskell
ResponseResult TextDocumentDefinition = Location |? (List Location |? List LocationLink)
```
<img width="665" alt="Screen Shot 2022-03-12 at 4 59 46 PM" src="https://user-images.githubusercontent.com/13156983/158040363-b88aa6b5-e1be-47bc-95b9-b9f95f5d2e9e.png">

I suppose it is possible to return `List []` instead of `null` because it should have the semantics though.

**Comment by michaelpj** [comment]
Related: https://github.com/haskell/lsp/issues/268

**Comment by michaelpj** [comment]
Fixed
