### ISSUE TITLE
HLS reports `LSP: no handler for: SMethod_SetTrace`

### ISSUE THREAD

**Issue by July541** [haskell/lsp#501]
After upgrading to HLS shipped with lsp-2.0, I often see this.

I've checked the log but haven't found any info.

![image](https://github.com/haskell/haskell-language-server/assets/16057632/ce43e6e5-0691-454d-825b-34caa33567a3)

**Comment by July541** [comment]
> https://github.com/haskell/lsp/blob/master/lsp/src/Language/LSP/Server/Processing.hs#L409

Something is wrong here, we just need to handle them correctly.

**Comment by michaelpj** [comment]
working on it
