### ISSUE TITLE
Different strategy about parsing `NotificationMessage`

### ISSUE THREAD

**Issue by July541** [haskell/lsp#508]
I just found generated model dropped `addNullField` for notification messages, which may be one of the causes of https://github.com/haskell/vscode-haskell/issues/920.

Does it intentionally?

/cc @michaelpj 

master:
https://github.com/haskell/lsp/blob/8ab6604fc7917c87379ff7198d43d78ba46d6026/lsp-types/src/Language/LSP/Protocol/Message/Types.hs#L111-L112

older:
https://github.com/haskell/lsp/blob/596376af3c9dff902797ef11f16ba6d177a22890/lsp-types/src/Language/LSP/Types/Message.hs#L260-L261

**Comment by michaelpj** [comment]
Argh, I suspect this is indeed a regression. Sorry about that. I'll try to get a fix out and included in the next HLS. Do you know if this change fixes the issue you saw?
