### ISSUE TITLE
Allow aeson-2.2

### ISSUE THREAD

**Issue by andreasabel** [haskell/lsp#524]
See
- https://github.com/commercialhaskell/stackage/issues/7031

Released version errors:
```
$ lsp-types-2.0.2.0$ cabal build --enable-tests -c 'aeson >= 2.2' --allow-newer -w ghc-9.8.1
...
src/Language/LSP/Protocol/Types/Common.hs:178:11: error: [GHC-83865]
    • Expecting one more argument to ‘KeyValue kv’
      Expected a constraint, but ‘KeyValue kv’ has kind ‘* -> Constraint’
    • In the type signature:
        (.=?) :: (KeyValue kv, ToJSON v) => String -> Maybe v -> [kv]
    |
178 | (.=?) :: (J.KeyValue kv, J.ToJSON v) => String -> Maybe v -> [kv]
    |           ^^^^^^^^^^^^^
```

**Comment by michaelpj** [comment]
Done

**Comment by andreasabel** [comment]
Btw, @michaelpj , maybe you want to become Stackage maintainer for `hls`?  There is currently none, I think.

**Comment by andreasabel** [comment]
The thing is that as Stackage maintainer you get alerted when you should update a dependency because you would otherwise fall out of Stackage (e.g. this very issue).
Otherwise, there isn't any additional "maintenance" to do you wouldn't do otherwise anyway.

Meta-comment: Why Stackage?  Because it gives a quality-stamp on its packages requiring to be up-to-date with the Haskell ecosystem (with a 6 month lag); something that Hackage does not provide.
